export type ShelterEntry = {
  id: string;
  name: string;
  operator: string;
  address: string;
  lat: number | null;
  lng: number | null;
  phone: string;
  email: string | null;
  website: string | null;
  populationServed: string[];
  ageRange: string;
  barrierLevel: 'low' | 'high' | 'transitional' | 'inclement-only';
  bedType: string[];
  totalBeds: number | null;
  bedsAvailable: number | null;
  hoursOpen: string;
  checkInWindow: string;
  services: string[];
  requiresSober: boolean;
  requiresNavigationCenterReferral?: boolean;
  petsAllowed: boolean | null;
  lastUpdated: string;
  notes: string;
  status: 'open' | 'full' | 'closed' | 'unknown' | 'inclement-only';
};

const NOW = new Date().toISOString();

export const shelters: ShelterEntry[] = [
  // ── REGULAR SHELTERS ───────────────────────────────────────────────────
  {
    id: 'house-of-charity',
    name: 'House of Charity',
    operator: 'Catholic Charities Eastern Washington',
    address: '32 W Pacific Ave, Spokane, WA 99201',
    lat: 47.6578,
    lng: -117.4265,
    phone: '509-624-7821',
    email: null,
    website: 'https://www.cceasternwa.org/house-of-charity',
    populationServed: ['Adult men'],
    ageRange: '18+',
    barrierLevel: 'low',
    bedType: ['Emergency overnight', 'Respite (medical recovery)'],
    totalBeds: 99,
    bedsAvailable: null,
    hoursOpen: 'Open 24 hours',
    checkInWindow: 'Check-in 5:00pm–8:00pm (3 first-responder beds available 9pm–midnight)',
    services: [
      '3 meals/day (breakfast 7:30am, lunch 11am)',
      'Showers',
      'Laundry',
      'Lockers',
      'Case management',
      'Workforce development',
      'Medical respite (Providence partnership)',
      'Mail service',
      'Recovery meetings',
    ],
    requiresSober: false,
    petsAllowed: false,
    lastUpdated: NOW,
    notes:
      "Longest-running shelter in Spokane (since 1958). Accepts anyone in any condition including active substance use. Must be able to self-care.",
    status: 'unknown',
  },
  {
    id: 'ugm-mens',
    name: "UGM Men's Shelter",
    operator: 'Union Gospel Mission of the Inland Northwest',
    address: '1224 E Trent Ave, Spokane, WA 99202',
    lat: 47.6655,
    lng: -117.3868,
    phone: '509-535-8510',
    email: 'deskman@uniongospelmission.org',
    website: 'https://www.uniongospelmission.org/need-help',
    populationServed: ['Adult men'],
    ageRange: '18+',
    barrierLevel: 'high',
    bedType: ['Emergency overnight', 'Short-term recovery'],
    totalBeds: 80,
    bedsAvailable: null,
    hoursOpen: 'Open 7am–7pm (24-hour emergency intake when temps ≤35°F)',
    checkInWindow: 'Check-in 7am–7pm',
    services: [
      'Meals (lunch 12pm, dinner 6pm)',
      'Showers',
      'Clothing',
      'Medical clinic',
      'Eye clinic',
      'Legal clinic',
      'Addiction recovery program',
      'Job training',
      'Spiritual support',
    ],
    requiresSober: true,
    petsAllowed: false,
    lastUpdated: NOW,
    notes:
      'Breathalyzer required at intake. Returning guests also require urinalysis. Clean and sober policy strictly enforced. Open 365 days/year.',
    status: 'unknown',
  },
  {
    id: 'ugm-crisis-women',
    name: 'UGM Crisis Shelter for Women & Children',
    operator: 'Union Gospel Mission of the Inland Northwest',
    address: '1515 E Illinois Ave, Spokane, WA 99207',
    lat: 47.6634,
    lng: -117.3698,
    phone: '509-535-0486',
    email: null,
    website: 'https://www.uniongospelmission.org/need-help',
    populationServed: ['Adult women', 'Women with children'],
    ageRange: '18+',
    barrierLevel: 'high',
    bedType: ['Emergency overnight', 'Crisis shelter'],
    totalBeds: 100,
    bedsAvailable: null,
    hoursOpen: 'Open 6am–9pm (24-hour emergency intake for women with children)',
    checkInWindow: 'Single women: 6am–9pm. Women with children: 24 hours',
    services: [
      'Meals',
      'Showers',
      'Clothing',
      'Case management',
      'Behavioral health counseling',
      "Children's programming",
      'Addiction recovery referrals',
    ],
    requiresSober: true,
    petsAllowed: false,
    lastUpdated: NOW,
    notes:
      'Breathalyzer required at intake. Women with children may check in at any hour. Licensed service/therapy animals only.',
    status: 'unknown',
  },
  {
    id: 'family-promise-open-doors',
    name: 'Family Promise Open Doors',
    operator: 'Family Promise of Spokane',
    address: '2002 E Mission Ave, Spokane, WA 99202',
    lat: 47.6672,
    lng: -117.3798,
    phone: '509-747-5487',
    email: 'office@familypromiseofspokane.org',
    website: 'https://www.familypromiseofspokane.org',
    populationServed: ['Families', 'Pregnant individuals'],
    ageRange: 'All ages (must be caring for a child 17 or younger, or pregnant)',
    barrierLevel: 'low',
    bedType: ['Emergency overnight', 'Family shelter'],
    totalBeds: 69,
    bedsAvailable: null,
    hoursOpen: 'Open 24 hours',
    checkInWindow: 'Call ahead to confirm space — do not walk in without calling',
    services: [
      'Meals',
      'Showers',
      'Laundry',
      'Kitchen access',
      'Food pantry',
      'Computers',
      'Case management',
      'School enrollment support',
      'Housing placement',
    ],
    requiresSober: false,
    petsAllowed: null,
    lastUpdated: NOW,
    notes:
      "Spokane's only 24/7 emergency shelter for families. Must be caring for a minor child (17 or younger) or be pregnant. Not for adults without children.",
    status: 'unknown',
  },
  {
    id: 'crosswalk-youth',
    name: 'Crosswalk Youth Shelter (VOA)',
    operator: 'Volunteers of America Eastern Washington',
    address: '525 W 2nd Ave, Spokane, WA 99201',
    lat: 47.6558,
    lng: -117.4228,
    phone: '509-688-1112',
    email: 'crosswalk@voaspokane.org',
    website: 'https://voaspokane.org/locations/crosswalk-youth-shelter/',
    populationServed: ['Youth'],
    ageRange: '13–17 (overnight); 18–21 (day services only)',
    barrierLevel: 'low',
    bedType: ['Emergency overnight', 'Youth crisis shelter'],
    totalBeds: 16,
    bedsAvailable: null,
    hoursOpen: 'Open 24 hours',
    checkInWindow: 'Weekdays: 10pm. Weekends: 10:30pm',
    services: [
      '3 meals/day',
      'Clothing',
      'Hygiene supplies',
      'Showers',
      'Laundry',
      'GED program',
      'Employment readiness',
      'Behavioral health counseling',
      'Substance use education',
      'Life skills training',
      'Family reconciliation services',
      'Bus passes',
    ],
    requiresSober: false,
    petsAllowed: false,
    lastUpdated: NOW,
    notes:
      'Only licensed emergency youth shelter in Eastern Washington (since 1985). Overnight stay for ages 13–17 only. Ages 18–21 may use day services. Call or walk in.',
    status: 'unknown',
  },
  {
    id: 'voa-young-adult',
    name: 'Young Adult Shelter (VOA)',
    operator: 'Volunteers of America Eastern Washington',
    address: '3104 E Augusta Ave, Spokane, WA 99207',
    lat: 47.6758,
    lng: -117.3658,
    phone: '509-990-0579',
    email: 'jmiller@voaspokane.org',
    website: 'https://voaspokane.org',
    populationServed: ['Adult men', 'Adult women'],
    ageRange: '18–24',
    barrierLevel: 'low',
    bedType: ['Emergency overnight'],
    totalBeds: 44,
    bedsAvailable: null,
    hoursOpen: 'Open 7:30pm–6:30am (check-in from 7:30pm, curfew 11pm)',
    checkInWindow: '7:30pm–10pm',
    services: [
      'Case management',
      'Housing placement',
      'Employment support',
      'Behavioral health referrals',
    ],
    requiresSober: false,
    petsAllowed: false,
    lastUpdated: NOW,
    notes:
      'For young adults ages 18–24 only. Overnight shelter only — closes at 6:30am. Case management available Mon–Fri during business hours at VOA main office.',
    status: 'unknown',
  },
  {
    id: 'cat-spokane',
    name: 'Compassionate Addiction Treatment (CAT)',
    operator: 'Compassionate Addiction Treatment',
    address: '960 E 3rd Ave, Spokane, WA 99202',
    lat: 47.6508,
    lng: -117.3948,
    phone: '509-919-3362',
    email: 'hello@catspokane.org',
    website: 'https://catspokane.org',
    populationServed: ['Adult men', 'Adult women'],
    ageRange: '18+',
    barrierLevel: 'low',
    bedType: ['Recovery housing', 'Transitional overnight'],
    totalBeds: 28,
    bedsAvailable: null,
    hoursOpen: 'Day program: Mon/Tue/Thu/Fri 8am–6pm, Wed 8am–5pm. Shelter: call for hours.',
    checkInWindow: 'Call for shelter check-in times',
    services: [
      'Peer-led recovery community',
      'Outpatient SUD treatment',
      'MAT (Suboxone)',
      'Housing support',
      'Employment navigation',
      'Street outreach',
      'Navigation assistance',
    ],
    requiresSober: false,
    petsAllowed: null,
    lastUpdated: NOW,
    notes:
      'Recovery-focused, low-barrier shelter and day program. Primarily serves those with substance use disorders. Walk-ins added to waitlist.',
    status: 'unknown',
  },
  {
    id: 'ywca-dv',
    name: 'YWCA Domestic Violence Shelter',
    operator: 'YWCA Spokane',
    address: 'Confidential — call for location',
    lat: null,
    lng: null,
    phone: '509-326-2255',
    email: 'help@ywcaspokane.org',
    website: 'https://ywcaspokane.org',
    populationServed: ['Domestic violence survivors', 'Adult women', 'Families'],
    ageRange: 'All ages',
    barrierLevel: 'low',
    bedType: ['Emergency DV shelter', 'Crisis shelter'],
    totalBeds: 20,
    bedsAvailable: null,
    hoursOpen: '24 hours / 7 days',
    checkInWindow: '24-hour crisis line — call anytime',
    services: [
      'Safety planning',
      'Legal advocacy',
      "Children's programming",
      'Case management',
      'Housing placement',
      'Support groups',
      'Counseling',
    ],
    requiresSober: false,
    petsAllowed: null,
    lastUpdated: NOW,
    notes:
      'For anyone fleeing intimate partner domestic violence — with or without children. Location is confidential for safety. Call or text 509-220-3725. Even when full, call for safety planning.',
    status: 'unknown',
  },
  {
    id: 'navigation-center',
    name: 'Navigation Center / Cannon Street',
    operator: 'City of Spokane / Revive Counseling Services',
    address: '527 S Cannon St, Spokane, WA 99201',
    lat: 47.6448,
    lng: -117.4295,
    phone: '509-755-2489',
    email: 'spokaneCHHS@spokanecity.org',
    website: 'https://my.spokanecity.org/navigationcenter/',
    populationServed: ['Adult men', 'Adult women'],
    ageRange: '18+',
    barrierLevel: 'low',
    bedType: ['Daytime services hub — no overnight beds on site'],
    totalBeds: null,
    bedsAvailable: null,
    hoursOpen: 'Daytime services — overnight beds accessed via referral',
    checkInWindow: 'Daytime walk-in for services; overnight bed referrals made here',
    services: [
      'Mental health services',
      'Addiction treatment referrals',
      'Housing placement',
      'Employment services',
      'Primary care connections',
      'Scatter-site overnight referrals',
    ],
    requiresSober: false,
    petsAllowed: null,
    lastUpdated: NOW,
    notes:
      "Entry point for City of Spokane's scatter-site shelter system. Come here first for overnight bed referrals to Cedar Center, Morning Star, Westminster, Knox, and other scatter sites.",
    status: 'open',
  },
  {
    id: 'jewels-general',
    name: 'Jewels Helping Hands — General Shelter',
    operator: 'Jewels Helping Hands',
    address: 'Confidential — call for location',
    lat: null,
    lng: null,
    phone: '509-723-6201',
    email: 'jewelshelpinghandsspokane@gmail.com',
    website: null,
    populationServed: ['Adult men', 'Adult women'],
    ageRange: '18+',
    barrierLevel: 'low',
    bedType: ['Emergency overnight'],
    totalBeds: 60,
    bedsAvailable: null,
    hoursOpen: '10pm–5am',
    checkInWindow: '10pm',
    services: ['Overnight shelter', 'Meals', 'Pets allowed'],
    requiresSober: false,
    petsAllowed: true,
    lastUpdated: NOW,
    notes: 'Pets welcome. Address undisclosed — call before arriving.',
    status: 'unknown',
  },
  {
    id: 'jewels-womens',
    name: "Jewels Helping Hands — Women's Shelter",
    operator: 'Jewels Helping Hands',
    address: 'Confidential — call for location',
    lat: null,
    lng: null,
    phone: '509-824-2312',
    email: 'jewelshelpinghandsspokane@gmail.com',
    website: null,
    populationServed: ['Adult women'],
    ageRange: '18+',
    barrierLevel: 'low',
    bedType: ['Emergency overnight'],
    totalBeds: 30,
    bedsAvailable: null,
    hoursOpen: '6pm–7:30am',
    checkInWindow: '6pm–7:30pm',
    services: [
      'Overnight shelter',
      'Meals',
      'Transportation provided',
      'Bed and belongings held during day',
    ],
    requiresSober: false,
    petsAllowed: null,
    lastUpdated: NOW,
    notes:
      'Women only. Beds and belongings held during the day. Meals and transportation provided. Address confidential for safety.',
    status: 'unknown',
  },
  {
    id: 'jewels-aurora',
    name: 'Jewels Helping Hands — Aurora Center (LGBTQIA+)',
    operator: 'Jewels Helping Hands',
    address: 'Confidential — call for location',
    lat: null,
    lng: null,
    phone: '509-710-9643',
    email: 'jewelshelpinghandsspokane@gmail.com',
    website: null,
    populationServed: ['LGBTQIA+'],
    ageRange: '25+',
    barrierLevel: 'low',
    bedType: ['Emergency overnight', 'Affirming shelter'],
    totalBeds: 15,
    bedsAvailable: null,
    hoursOpen: 'Call for hours',
    checkInWindow: 'Call ahead',
    services: ['LGBTQIA+-affirming overnight shelter', 'Peer support', 'Case management'],
    requiresSober: false,
    petsAllowed: null,
    lastUpdated: NOW,
    notes: 'For LGBTQIA+ adults 25 and older. Address confidential for safety.',
    status: 'unknown',
  },

  // ── INCLEMENT WEATHER SHELTERS ─────────────────────────────────────────
  {
    id: 'salvation-army-way-out',
    name: 'Salvation Army Way Out (Inclement Weather)',
    operator: 'Salvation Army Spokane Citadel Corps',
    address: '55 W Mission Ave, Spokane, WA 99201',
    lat: 47.6612,
    lng: -117.4268,
    phone: '509-866-5476',
    email: 'karen.whitman@usw.salvationarmy.org',
    website: null,
    populationServed: ['Adult men', 'Adult women'],
    ageRange: '18+',
    barrierLevel: 'inclement-only',
    bedType: ['Inclement weather overnight'],
    totalBeds: 25,
    bedsAvailable: null,
    hoursOpen: '7pm–7am (activated by City of Spokane during weather emergencies only)',
    checkInWindow: '7pm — no loitering before check-in. Enter from Atlantic St & Mission Ave basement door.',
    services: ['Overnight shelter', 'Basic amenities'],
    requiresSober: false,
    petsAllowed: false,
    lastUpdated: NOW,
    notes:
      'Only opens during city-declared weather emergencies. Must be able to self-care independently.',
    status: 'inclement-only',
  },
  {
    id: 'hoc-inclement',
    name: 'House of Charity — Inclement Weather Surge',
    operator: 'Catholic Charities Eastern Washington',
    address: '527 S Cannon St, Spokane, WA 99201',
    lat: 47.6448,
    lng: -117.4295,
    phone: '509-507-4624',
    email: null,
    website: null,
    populationServed: ['Adult men'],
    ageRange: '18+',
    barrierLevel: 'inclement-only',
    bedType: ['Inclement weather overnight'],
    totalBeds: 35,
    bedsAvailable: null,
    hoursOpen: 'Check-in 9am–8pm (activated during weather emergencies)',
    checkInWindow: '9am–8pm when activated — referral from Navigation Center',
    services: ['Overnight surge shelter'],
    requiresSober: false,
    requiresNavigationCenterReferral: true,
    petsAllowed: false,
    lastUpdated: NOW,
    notes:
      'Surge capacity for inclement weather events. Referral required from Navigation Center at 527 S Cannon St.',
    status: 'inclement-only',
  },
  {
    id: 'jewels-inclement-women',
    name: "Jewels — Inclement Weather Women's Shelter",
    operator: 'Jewels Helping Hands',
    address: '3909 W Rowan Ave, Spokane, WA 99205',
    lat: 47.6732,
    lng: -117.4712,
    phone: '509-638-4493',
    email: 'jewelshelpinghandsspokane@gmail.com',
    website: null,
    populationServed: ['Adult women'],
    ageRange: '18+',
    barrierLevel: 'inclement-only',
    bedType: ['Inclement weather overnight'],
    totalBeds: 15,
    bedsAvailable: null,
    hoursOpen: '6pm onward when activated by City of Spokane',
    checkInWindow: '6pm when activated',
    services: ['Overnight shelter', 'Basic amenities'],
    requiresSober: false,
    petsAllowed: null,
    lastUpdated: NOW,
    notes: 'Women only. Only activates during city-declared weather emergencies.',
    status: 'inclement-only',
  },
  {
    id: 'revive-inclement',
    name: 'Revive — Inclement Weather Shelter',
    operator: 'Revive Counseling Services',
    address: 'Undisclosed — call for location',
    lat: null,
    lng: null,
    phone: '509-413-2950',
    email: 'shelterme@revivespokane.com',
    website: null,
    populationServed: ['Adult men', 'Adult women'],
    ageRange: '18+',
    barrierLevel: 'inclement-only',
    bedType: ['Inclement weather overnight'],
    totalBeds: 15,
    bedsAvailable: null,
    hoursOpen: '5:30pm–8pm check-in when activated',
    checkInWindow: '5:30pm–8pm. No drop-offs.',
    services: ['Overnight shelter'],
    requiresSober: false,
    petsAllowed: false,
    lastUpdated: NOW,
    notes:
      'Must be able to perform all activities of daily living (ADLs) independently. No drop-offs. Activates during city-declared weather emergencies.',
    status: 'inclement-only',
  },
];
